### ISSUE TITLE
Sitting days option

### ISSUE THREAD

**Issue by samsmith** [fantasticlife/egg-timer#6]
it would be useful to have a "sitting days" option (more) clearly called that in the choices of period to calculate on the home page:
https://parliament-calendar.herokuapp.com

(but this is really useful as it is)

**Comment by fantasticlife** [comment]
Sorry, don't think I understand the request....
You need to specify the procedure because different legislation defines "sitting day" differently.
https://github.com/fantasticlife/egg-timer/blob/master/lib/monkey_patching/date.rb#L141

**Comment by samsmith** [comment]
Sometimes, it just seems to be stated as "sitting day" - none of the options seemed to give me the September date that seems to be expected for this:
e.g. https://ico.org.uk/for-organisations/data-sharing-a-code-of-practice/ (which is what started me down this rabbit hole)

Which in practice, is 40 sitting days in each house (but not necessarily the same days); would probably need both figures as it matters to the Lords (which might care in this case) separately to the Commons (which in this case wont care). 

The definition I used was the one from your very helpful sitting day calendar

**Comment by fantasticlife** [comment]
Librarian Jayne says that was laid under a negative procedure on 18th May:
https://commonsbusiness.parliament.uk/document/47618/html#anchor-55
So you'd need to choose the "Negative Statutory Instrument praying period (Commons and Lords)" option.

Shout if that doesn't return the date expected.

**Comment by samsmith** [comment]
Thank Librarian Jayne for that helpful reference.

Prior to checking, my expectation was that it would come into force after the summer, the text on the ICO website says it hasn't yet come into force (which could be wrong but ICO is the regulator and author), and some manual counting using the monthly pages suggest that the period would expire sometime around the week of 13th September (ish)
	https://parliament-calendar.herokuapp.com/calendar/2021/5  (etc)

Saying it was laid on 18th May, Negative praying, scrutiny period of 40 days, the calculator says 6th July:
	https://parliament-calendar.herokuapp.com/calculator/calculate?start-date=2021-05-18&procedure=6&day-count=40 

I originally assumed this was me not finding the right option to press in the list, since a few of the different options gave the same date, and it wasn't close to September...

Perhaps something else is going on if the above is indeed the right info.

**Comment by JayneSunley** [comment]
Morning Sam! 

Counting on fingers suggests the 6th July is correct: 

Date | Commons | Lords | Count

18/05/2021 | TRUE | TRUE | 1
19/05/2021 | TRUE | TRUE | 2
20/05/2021 | TRUE | TRUE | 3
21/05/2021 | TRUE | TRUE | 4
22/05/2021 | TRUE | TRUE | 5
23/05/2021 | TRUE | TRUE | 6
24/05/2021 | TRUE | TRUE | 7
25/05/2021 | TRUE | TRUE | 8
26/05/2021 | TRUE | TRUE | 9
27/05/2021 | TRUE | TRUE | 10
28/05/2021 | FALSE | FALSE | 10
29/05/2021 | FALSE | FALSE | 10
30/05/2021 | FALSE | FALSE | 10
31/05/2021 | FALSE | FALSE | 10
01/06/2021 | FALSE | FALSE | 10
02/06/2021 | FALSE | FALSE | 10
03/06/2021 | FALSE | FALSE | 10
04/06/2021 | FALSE | FALSE | 10
05/06/2021 | FALSE | FALSE | 10
06/06/2021 | FALSE | FALSE | 10
07/06/2021 | TRUE | TRUE | 11
08/06/2021 | TRUE | TRUE | 12
09/06/2021 | TRUE | TRUE | 13
10/06/2021 | TRUE | TRUE | 14
11/06/2021 | TRUE | TRUE | 15
12/06/2021 | TRUE | TRUE | 16
13/06/2021 | TRUE | TRUE | 17
14/06/2021 | TRUE | TRUE | 18
15/06/2021 | TRUE | TRUE | 19
16/06/2021 | TRUE | TRUE | 20
17/06/2021 | TRUE | TRUE | 21
18/06/2021 | TRUE | TRUE | 22
19/06/2021 | TRUE | TRUE | 23
20/06/2021 | TRUE | TRUE | 24
21/06/2021 | TRUE | TRUE | 25
22/06/2021 | TRUE | TRUE | 26
23/06/2021 | TRUE | TRUE | 27
24/06/2021 | TRUE | TRUE | 28
25/06/2021 | TRUE | TRUE | 29
26/06/2021 | TRUE | TRUE | 30
27/06/2021 | TRUE | TRUE | 31
28/06/2021 | TRUE | TRUE | 32
29/06/2021 | TRUE | TRUE | 33
30/06/2021 | TRUE | TRUE | 34
01/07/2021 | TRUE | TRUE | 35
02/07/2021 | TRUE | TRUE | 36
03/07/2021 | TRUE | TRUE | 37
04/07/2021 | TRUE | TRUE | 38
05/07/2021 | TRUE | TRUE | 39
06/07/2021 | TRUE | TRUE | 40

Weekends, strangely, count in a negative 40 day period. The only time the clock stopped during the period was when the House(s) rose for the Whitsun recess. The count restarted on 7th June. I hope that helps! 

In terms of the Code of Practice coming into force it may well be that the website hasn't updated or is, perhaps, working on an assumption users will know when the period is up. We find with indexing of laid papers that the accuracy of websites can be a bit hit and miss. It might be worth dropping them an email to confirm its status.

**Comment by fantasticlife** [comment]
The problem tends to be that documents often talk in terms of sitting days but legislation varies on what that means. Sometimes it literally means sitting days, sometimes it's sitting days but not counting if EITHER House rises for more than four days, sometimes it's sitting days but not counting if BOTH Houses rise and etc. If you're not sure you have to work back from the enabling legislation to work out what rules you need to follow. Even the definition of "sitting day" within those rulesets can vary with some Acts counting an overnight sitting as one day and some counting it as two. I have no idea if drafters intend these discrepancies. But referring to sitting days can be misleading.

**Comment by samsmith** [comment]
thanks
